export enum Routes {
  AUTH = 'auth',
  USER = 'user',
  DISCORD = 'discord',
  YOUTUBE = 'youtube',
  OPENAI = 'openai',
  BRAWL_STARS = 'brawl-stars',
}

export enum Services {
  AUTH_SERVICE = 'AUTH_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  DISCORD_SERVICE = 'DISCORD_SERVICE',
  DISCORD_HTTP_SERVICE = 'DISCORD_HTTP_SERVICE',
  YOUTUBE_SERVICE = 'YOUTUBE_SERVICE',
  OPENAI_SERVICE = 'OPENAI_SERVICE',
  BRAWL_STARS_SERVICE = 'BRAWL_STARS_SERVICE',
}
