// This file is auto-generated by @hey-api/openapi-ts

export const $UserDto = {
    type: 'object',
    properties: {
        discordId: {
            type: 'string'
        },
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        username: {
            type: 'string'
        },
        discriminator: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        }
    },
    required: ['discordId', 'accessToken', 'refreshToken', 'username', 'discriminator', 'avatar']
} as const;

export const $UpdateWalletBalanceDto = {
    type: 'object',
    properties: {
        coins: {
            type: 'number'
        },
        powerpoints: {
            type: 'number'
        }
    },
    required: ['coins', 'powerpoints']
} as const;

export const $WalletCollectableDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        price: {
            type: 'number'
        },
        imageUrl: {
            type: 'string'
        }
    },
    required: ['id', 'name', 'price', 'imageUrl']
} as const;

export const $WalletDto = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        coins: {
            type: 'number'
        },
        powerpoints: {
            type: 'number'
        },
        collectables: {
            default: [],
            type: 'array',
            items: {
                '$ref': '#/components/schemas/WalletCollectableDto'
            }
        }
    },
    required: ['userId', 'coins', 'powerpoints', 'collectables']
} as const;

export const $PartialGuildDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        icon: {
            type: 'string'
        },
        owner: {
            type: 'boolean'
        },
        permissions: {
            type: 'number'
        },
        features: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        isActive: {
            type: 'boolean'
        }
    },
    required: ['id', 'name', 'icon', 'owner', 'permissions', 'features', 'isActive']
} as const;

export const $GuildChannelDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        type: {
            type: 'number'
        }
    },
    required: ['id', 'name', 'type']
} as const;

export const $WelcomeMessageDto = {
    type: 'object',
    properties: {
        guildId: {
            type: 'string'
        },
        channelId: {
            type: 'string'
        }
    },
    required: ['guildId', 'channelId']
} as const;

export const $CreateMemberCountDto = {
    type: 'object',
    properties: {
        channelId: {
            type: 'string'
        }
    },
    required: ['channelId']
} as const;

export const $GuildMemberCountDto = {
    type: 'object',
    properties: {
        guildId: {
            type: 'string'
        },
        channelId: {
            type: 'string'
        }
    },
    required: ['guildId', 'channelId']
} as const;

export const $CreateYoutubeChannelDto = {
    type: 'object',
    properties: {
        guildId: {
            type: 'string'
        },
        apiKey: {
            type: 'string'
        },
        channelId: {
            type: 'string'
        },
        guildChannelId: {
            type: 'string'
        },
        roleId: {
            type: 'string'
        },
        latestVideoDateTime: {
            type: 'string'
        },
        isActive: {
            type: 'boolean'
        }
    },
    required: ['guildId', 'apiKey', 'channelId', 'guildChannelId', 'roleId', 'latestVideoDateTime', 'isActive']
} as const;

export const $YoutubeChannelDto = {
    type: 'object',
    properties: {
        guildId: {
            type: 'string'
        },
        guildChannelId: {
            type: 'string'
        },
        latestVideoDateTime: {
            type: 'string'
        },
        roleId: {
            type: 'string'
        }
    },
    required: ['guildId', 'guildChannelId', 'latestVideoDateTime', 'roleId']
} as const;

export const $YoutubeVideoDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        publishedAt: {
            type: 'string'
        },
        channelTitle: {
            type: 'string'
        },
        channelId: {
            type: 'string'
        },
        videoTitle: {
            type: 'string'
        },
        videoUrl: {
            type: 'string'
        },
        thumbnailUrl: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    required: ['id', 'publishedAt', 'channelTitle', 'channelId', 'videoTitle', 'videoUrl', 'thumbnailUrl']
} as const;

export const $CreateImageDto = {
    type: 'object',
    properties: {
        prompt: {
            type: 'string'
        }
    },
    required: ['prompt']
} as const;

export const $ImageDto = {
    type: 'object',
    properties: {
        url: {
            type: 'string'
        }
    },
    required: ['url']
} as const;

export const $UpsertBrawlStarsUserDto = {
    type: 'object',
    properties: {
        userId: {
            type: 'string'
        },
        tag: {
            type: 'string'
        }
    },
    required: ['userId', 'tag']
} as const;

export const $BrawlStarsUserDto = {
    type: 'object',
    properties: {
        tag: {
            type: 'number'
        }
    },
    required: ['tag']
} as const;

export const $BrawlStarsEventDto = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        mode: {
            type: 'string'
        },
        map: {
            type: 'string'
        }
    },
    required: ['id', 'mode', 'map']
} as const;

export const $BrawlStarsMapDto = {
    type: 'object',
    properties: {
        startTime: {
            type: 'string'
        },
        endTime: {
            type: 'string'
        },
        slotId: {
            type: 'number'
        },
        event: {
            '$ref': '#/components/schemas/BrawlStarsEventDto'
        }
    },
    required: ['startTime', 'endTime', 'slotId', 'event']
} as const;

export const $IconDto = {
    type: 'object',
    properties: {
        id: {
            type: 'number'
        }
    },
    required: ['id']
} as const;

export const $ClubDto = {
    type: 'object',
    properties: {
        tag: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        badgeId: {
            type: 'number'
        },
        trophies: {
            type: 'number'
        },
        rank: {
            type: 'number'
        },
        memberCount: {
            type: 'number'
        }
    },
    required: ['tag', 'name']
} as const;

export const $BrawlerDto = {
    type: 'object',
    properties: {
        id: {
            type: 'number'
        },
        name: {
            type: 'string'
        },
        power: {
            type: 'number'
        },
        rank: {
            type: 'number'
        },
        trophies: {
            type: 'number'
        },
        highestTrophies: {
            type: 'number'
        },
        gears: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        starPowers: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        gadgets: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['id', 'name', 'power', 'rank', 'trophies', 'highestTrophies', 'gears', 'starPowers', 'gadgets']
} as const;

export const $PlayerDto = {
    type: 'object',
    properties: {
        tag: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        nameColor: {
            type: 'string'
        },
        icon: {
            '$ref': '#/components/schemas/IconDto'
        },
        trophies: {
            type: 'number'
        },
        highestTrophies: {
            type: 'number'
        },
        highestPowerPlayPoints: {
            type: 'number'
        },
        expLevel: {
            type: 'number'
        },
        expPoints: {
            type: 'number'
        },
        isQualifiedFromChampionshipChallenge: {
            type: 'boolean'
        },
        '3vs3Victories': {
            type: 'number'
        },
        soloVictories: {
            type: 'number'
        },
        duoVictories: {
            type: 'number'
        },
        bestRoboRumbleTime: {
            type: 'number'
        },
        bestTimeAsBigBrawler: {
            type: 'number'
        },
        club: {
            '$ref': '#/components/schemas/ClubDto'
        },
        brawlers: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BrawlerDto'
            }
        }
    },
    required: ['tag', 'name', 'nameColor', 'icon', 'trophies']
} as const;